language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install --prefer-dist --dev

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - ./vendor/bin/phpdoc -t doc -f ActiveRecord.php
  - cd doc
  - git init
  - git config user.name "Travis CI"
  - git config user.email "lloydzhou@qq.com"
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://$GH_TOKEN@$GH_REF" master:gh-pages > /dev/null 2>&1
